from argparse import ArgumentParser
from pathlib import Path
import time
import traceback

import numpy as np
from isaacsim import SimulationApp


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCENE = PROJECT_ROOT / "outputs" / "isaac" / "desert_heightfield_scene.usd"
DEFAULT_PATH = PROJECT_ROOT / "outputs" / "perception" / "local_path.npz"
ROVER_PATH = "/World/RoverPlaceholder"
LIVE_ROVER_ROOT = "/World/LiveRover"
CHASSIS_SCALE = (0.62, 0.36, 0.12)
WHEEL_BASE = 0.92
WHEEL_TRACK = 0.72
WHEEL_RADIUS = 0.18
WHEEL_WIDTH = 0.16
SUSPENSION_CLEARANCE = 0.08
CHASSIS_CENTER_Z = WHEEL_RADIUS + SUSPENSION_CLEARANCE + CHASSIS_SCALE[2]
SENSOR_CENTER_Z = CHASSIS_CENTER_Z + 0.35


def parse_args():
    parser = ArgumentParser(description="Show a live rover path demo in Isaac Sim GUI.")
    parser.add_argument("--scene", default=str(DEFAULT_SCENE), help="USD scene to open.")
    parser.add_argument("--path", default=str(DEFAULT_PATH), help="local_path.npz generated by local planner.")
    parser.add_argument(
        "--demo",
        choices=("1", "2"),
        default="1",
        help="Path demo: 1=planned endpoint path, 2=uphill climb.",
    )
    parser.add_argument("--speed", type=float, default=1.0, help="Rover speed in meters per second.")
    parser.add_argument(
        "--max-tilt-degrees",
        type=float,
        default=22.0,
        help="Maximum visual pitch/roll angle applied from terrain slope.",
    )
    parser.add_argument(
        "--frames",
        type=int,
        default=0,
        help="Number of frames to run before exit. 0 means run until the window closes.",
    )
    parser.add_argument(
        "--loop",
        action="store_true",
        help="Loop back to the start after reaching the end of the path.",
    )
    return parser.parse_args()


args = parse_args()
scene_path = Path(args.scene).expanduser().resolve()
path_path = Path(args.path).expanduser().resolve()

if not scene_path.exists():
    raise FileNotFoundError(f"USD scene does not exist: {scene_path}")
if not path_path.exists():
    raise FileNotFoundError(f"local path does not exist: {path_path}")
if args.speed <= 0:
    raise ValueError("speed must be positive")
if args.max_tilt_degrees <= 0:
    raise ValueError("max-tilt-degrees must be positive")
if args.frames < 0:
    raise ValueError("frames must be non-negative")

simulation_app = SimulationApp({"headless": False, "open_usd": str(scene_path)})

import omni.usd  # noqa: E402
from pxr import Gf, Sdf, UsdGeom  # noqa: E402


def main() -> None:
    stage = _wait_for_stage()

    terrain_sampler = _load_terrain_sampler(stage)
    world_points = _load_demo_path(terrain_sampler, args.demo)
    if len(world_points) < 2:
        raise RuntimeError("local path must contain at least two points")

    rover = _create_live_rover(stage)
    _hide_legacy_goal_marker(stage)
    _draw_path_markers(stage, world_points, terrain_sampler)
    _set_overhead_camera(stage, world_points)
    _set_active_camera()

    cumulative_distance = _cumulative_distance(world_points)
    total_distance = float(cumulative_distance[-1])
    start_time = time.monotonic()
    frame_count = 0

    print(f"Opened scene: {scene_path}", flush=True)
    print(f"Loaded path points: {len(world_points)}", flush=True)
    print(f"Demo path: {args.demo}", flush=True)
    print(f"Path length: {total_distance:.2f} m", flush=True)
    print("Close the Isaac window to stop the demo.", flush=True)

    while simulation_app.is_running():
        elapsed = time.monotonic() - start_time
        distance = elapsed * args.speed
        if args.loop:
            distance %= total_distance
        else:
            distance = min(distance, total_distance)
        position = _interpolate_path(world_points, cumulative_distance, distance)
        direction = _direction_at_distance(world_points, cumulative_distance, distance)
        _set_live_rover_pose(rover, terrain_sampler, position, direction)
        simulation_app.update()

        frame_count += 1
        if args.frames and frame_count >= args.frames:
            break


def _wait_for_stage():
    usd_context = omni.usd.get_context()
    for _ in range(60):
        simulation_app.update()
        stage = usd_context.get_stage()
        if stage is not None:
            return stage
    raise RuntimeError("Isaac USD stage was not loaded")


def _load_demo_path(terrain_sampler, demo: str) -> list[Gf.Vec3f]:
    if demo == "1":
        return _load_planned_path(terrain_sampler)
    return _make_uphill_path(terrain_sampler)


def _load_planned_path(terrain_sampler) -> list[Gf.Vec3f]:
    path_data = np.load(path_path)

    path = path_data["path"]
    origin_xy = path_data["origin_xy"].astype(np.float32)
    resolution = float(path_data["resolution"])

    points: list[Gf.Vec3f] = []
    for row, col in path:
        row = int(row)
        col = int(col)
        x = float(origin_xy[0] + col * resolution)
        y = float(origin_xy[1] + row * resolution)
        points.append(Gf.Vec3f(x, y, terrain_sampler.sample(x, y)))
    return points


def _make_uphill_path(terrain_sampler) -> list[Gf.Vec3f]:
    elevation = terrain_sampler.elevation
    low_row, low_col = np.unravel_index(int(np.argmin(elevation)), elevation.shape)
    high_row, high_col = np.unravel_index(int(np.argmax(elevation)), elevation.shape)

    start = np.asarray([terrain_sampler.x_values[low_col], terrain_sampler.y_values[low_row]], dtype=np.float32)
    goal = np.asarray([terrain_sampler.x_values[high_col], terrain_sampler.y_values[high_row]], dtype=np.float32)
    distance = float(np.linalg.norm(goal - start))
    count = max(24, int(distance / 0.25))

    points: list[Gf.Vec3f] = []
    for fraction in np.linspace(0.0, 1.0, count):
        xy = start + (goal - start) * float(fraction)
        x = float(xy[0])
        y = float(xy[1])
        points.append(Gf.Vec3f(x, y, terrain_sampler.sample(x, y)))
    return points


def _load_terrain_sampler(stage):
    mesh = UsdGeom.Mesh(stage.GetPrimAtPath("/World/DesertTerrain"))
    if not mesh.GetPrim().IsValid():
        raise RuntimeError("Terrain prim does not exist: /World/DesertTerrain")

    points = np.asarray([[float(point[0]), float(point[1]), float(point[2])] for point in mesh.GetPointsAttr().Get()])
    if points.ndim != 2 or points.shape[1] != 3 or len(points) == 0:
        raise RuntimeError("Terrain mesh contains no points")

    x_values = np.unique(points[:, 0])
    y_values = np.unique(points[:, 1])
    if x_values.size * y_values.size != points.shape[0]:
        raise RuntimeError("Terrain mesh is not a regular heightfield grid")

    order = np.lexsort((points[:, 0], points[:, 1]))
    z_grid = points[order, 2].reshape(y_values.size, x_values.size)
    return _TerrainSampler(x_values=x_values, y_values=y_values, elevation=z_grid)


class _TerrainSampler:
    def __init__(self, x_values: np.ndarray, y_values: np.ndarray, elevation: np.ndarray) -> None:
        self.x_values = x_values.astype(np.float32)
        self.y_values = y_values.astype(np.float32)
        self.elevation = elevation.astype(np.float32)

    def sample(self, x: float, y: float) -> float:
        x = float(np.clip(x, self.x_values[0], self.x_values[-1]))
        y = float(np.clip(y, self.y_values[0], self.y_values[-1]))

        col = int(np.searchsorted(self.x_values, x, side="right") - 1)
        row = int(np.searchsorted(self.y_values, y, side="right") - 1)
        col = max(0, min(col, self.x_values.size - 2))
        row = max(0, min(row, self.y_values.size - 2))

        x0 = float(self.x_values[col])
        x1 = float(self.x_values[col + 1])
        y0 = float(self.y_values[row])
        y1 = float(self.y_values[row + 1])
        x_fraction = 0.0 if x1 == x0 else (x - x0) / (x1 - x0)
        y_fraction = 0.0 if y1 == y0 else (y - y0) / (y1 - y0)

        z00 = float(self.elevation[row, col])
        z01 = float(self.elevation[row, col + 1])
        z10 = float(self.elevation[row + 1, col])
        z11 = float(self.elevation[row + 1, col + 1])
        return (
            z00 * (1.0 - y_fraction) * (1.0 - x_fraction)
            + z01 * (1.0 - y_fraction) * x_fraction
            + z10 * y_fraction * (1.0 - x_fraction)
            + z11 * y_fraction * x_fraction
        )

    def normal(self, x: float, y: float) -> tuple[float, float, float]:
        dx = float(np.median(np.diff(self.x_values)))
        dy = float(np.median(np.diff(self.y_values)))
        dz_dx = (self.sample(x + dx, y) - self.sample(x - dx, y)) / max(2.0 * dx, 1e-6)
        dz_dy = (self.sample(x, y + dy) - self.sample(x, y - dy)) / max(2.0 * dy, 1e-6)
        normal = np.asarray([-dz_dx, -dz_dy, 1.0], dtype=np.float32)
        normal /= max(float(np.linalg.norm(normal)), 1e-6)
        return float(normal[0]), float(normal[1]), float(normal[2])


def _draw_path_markers(stage, points: list[Gf.Vec3f], terrain_sampler) -> None:
    _draw_disk(stage, "/World/LivePath/Start", points[0], terrain_sampler, radius=0.24, color=(0.0, 0.45, 1.0))
    _draw_flag(stage, points[-1], terrain_sampler)
    _draw_path_ribbon(stage, points, terrain_sampler)
    stride = max(1, len(points) // 40)
    for index, point in enumerate(points[::stride]):
        marker = _draw_disk(
            stage,
            f"/World/LivePath/Point_{index:03d}",
            point,
            terrain_sampler,
            radius=0.055,
            color=(1.0, 0.88, 0.22),
        )
        marker.GetPrim().SetActive(True)


def _draw_path_ribbon(stage, points: list[Gf.Vec3f], terrain_sampler) -> None:
    for index, (start, end) in enumerate(zip(points[:-1], points[1:])):
        dx = float(end[0] - start[0])
        dy = float(end[1] - start[1])
        length = float(np.hypot(dx, dy))
        if length < 1e-6:
            continue
        center_x = float((start[0] + end[0]) * 0.5)
        center_y = float((start[1] + end[1]) * 0.5)
        center_z = terrain_sampler.sample(center_x, center_y) + 0.08
        center = Gf.Vec3f(
            center_x,
            center_y,
            center_z,
        )
        yaw = float(np.degrees(np.arctan2(dy, dx)))
        segment = UsdGeom.Cube.Define(stage, f"/World/LivePath/Ribbon_{index:03d}")
        segment.CreateSizeAttr(1.0)
        segment.CreateDisplayColorAttr([Gf.Vec3f(0.0, 0.22, 1.0)])
        _set_static_transform(
            segment.GetPrim(),
            translate=center,
            rotate=Gf.Vec3f(0.0, 0.0, yaw),
            scale=Gf.Vec3f(length * 0.5, 0.035, 0.006),
        )


def _draw_disk(
    stage,
    path: str,
    position: Gf.Vec3f,
    terrain_sampler,
    radius: float,
    color: tuple[float, float, float],
) -> UsdGeom.Cylinder:
    disk = UsdGeom.Cylinder.Define(stage, path)
    disk.CreateRadiusAttr(radius)
    disk.CreateHeightAttr(0.035)
    z = terrain_sampler.sample(float(position[0]), float(position[1])) + 0.08
    _set_translate(disk.GetPrim(), Gf.Vec3f(float(position[0]), float(position[1]), z))
    disk.CreateDisplayColorAttr([Gf.Vec3f(*color)])
    return disk


def _draw_flag(stage, position: Gf.Vec3f, terrain_sampler) -> None:
    z = terrain_sampler.sample(float(position[0]), float(position[1]))
    pole = UsdGeom.Cylinder.Define(stage, "/World/LivePath/Goal/Pole")
    pole.CreateRadiusAttr(0.025)
    pole.CreateHeightAttr(0.7)
    _set_translate(pole.GetPrim(), Gf.Vec3f(float(position[0]), float(position[1]), z + 0.35))
    pole.CreateDisplayColorAttr([Gf.Vec3f(0.95, 0.95, 0.95)])

    flag = UsdGeom.Cube.Define(stage, "/World/LivePath/Goal/Flag")
    flag.CreateSizeAttr(1.0)
    _set_static_transform(
        flag.GetPrim(),
        translate=Gf.Vec3f(float(position[0]) + 0.18, float(position[1]), z + 0.62),
        rotate=Gf.Vec3f(0.0, 0.0, 0.0),
        scale=Gf.Vec3f(0.24, 0.035, 0.12),
    )
    flag.CreateDisplayColorAttr([Gf.Vec3f(1.0, 0.08, 0.04)])


def _hide_legacy_goal_marker(stage) -> None:
    goal = stage.GetPrimAtPath("/World/PlantingGoal")
    if goal.IsValid():
        goal.SetActive(False)


def _create_live_rover(stage) -> dict[str, object]:
    placeholder = stage.GetPrimAtPath(ROVER_PATH)
    if placeholder.IsValid():
        placeholder.SetActive(False)

    root = UsdGeom.Xform.Define(stage, LIVE_ROVER_ROOT)
    root_op = _create_transform_op(root.GetPrim())

    chassis = UsdGeom.Cube.Define(stage, f"{LIVE_ROVER_ROOT}/Chassis")
    chassis.CreateSizeAttr(1.0)
    chassis.CreateDisplayColorAttr([Gf.Vec3f(0.08, 0.14, 0.13)])
    _create_static_part_pose(
        chassis.GetPrim(),
        translate=Gf.Vec3f(0.0, 0.0, CHASSIS_CENTER_Z),
        rotate=Gf.Vec3f(0.0, 0.0, 0.0),
        scale=Gf.Vec3f(*CHASSIS_SCALE),
    )

    sensor = UsdGeom.Cube.Define(stage, f"{LIVE_ROVER_ROOT}/SensorMast")
    sensor.CreateSizeAttr(1.0)
    sensor.CreateDisplayColorAttr([Gf.Vec3f(0.08, 0.10, 0.12)])
    _create_static_part_pose(
        sensor.GetPrim(),
        translate=Gf.Vec3f(0.0, 0.0, SENSOR_CENTER_Z),
        rotate=Gf.Vec3f(0.0, 0.0, 0.0),
        scale=Gf.Vec3f(0.08, 0.08, 0.34),
    )

    arrow = UsdGeom.Cone.Define(stage, f"{LIVE_ROVER_ROOT}/ForwardArrow")
    arrow.CreateRadiusAttr(0.08)
    arrow.CreateHeightAttr(0.26)
    arrow.CreateAxisAttr("X")
    arrow.CreateDisplayColorAttr([Gf.Vec3f(1.0, 0.04, 0.02)])
    _create_static_part_pose(
        arrow.GetPrim(),
        translate=Gf.Vec3f(0.62, 0.0, CHASSIS_CENTER_Z + 0.08),
        rotate=Gf.Vec3f(0.0, 0.0, 0.0),
    )

    for name, local_position in _wheel_local_positions().items():
        wheel = UsdGeom.Cylinder.Define(stage, f"{LIVE_ROVER_ROOT}/Wheel_{name}")
        wheel.CreateRadiusAttr(WHEEL_RADIUS)
        wheel.CreateHeightAttr(WHEEL_WIDTH)
        wheel.CreateAxisAttr("Y")
        wheel.CreateDisplayColorAttr([Gf.Vec3f(0.015, 0.015, 0.014)])
        _create_static_part_pose(wheel.GetPrim(), translate=local_position, rotate=Gf.Vec3f(0.0, 0.0, 0.0))

        hub = UsdGeom.Cylinder.Define(stage, f"{LIVE_ROVER_ROOT}/Hub_{name}")
        hub.CreateRadiusAttr(WHEEL_RADIUS * 0.42)
        hub.CreateHeightAttr(WHEEL_WIDTH * 1.08)
        hub.CreateAxisAttr("Y")
        hub.CreateDisplayColorAttr([Gf.Vec3f(0.48, 0.50, 0.47)])
        _create_static_part_pose(hub.GetPrim(), translate=local_position, rotate=Gf.Vec3f(0.0, 0.0, 0.0))

    return {"root_transform": root_op}


def _create_transform_op(prim):
    xform = UsdGeom.Xformable(prim)
    xform.ClearXformOpOrder()
    return xform.AddTransformOp()


def _create_static_part_pose(
    prim,
    translate: Gf.Vec3f,
    rotate: Gf.Vec3f,
    scale: Gf.Vec3f | None = None,
) -> None:
    xform = UsdGeom.Xformable(prim)
    xform.ClearXformOpOrder()
    if scale is not None:
        xform.AddScaleOp().Set(scale)
    xform.AddRotateXYZOp().Set(rotate)
    xform.AddTranslateOp().Set(translate)


def _set_static_transform(
    prim,
    translate: Gf.Vec3f,
    rotate: Gf.Vec3f,
    scale: Gf.Vec3f | None = None,
) -> None:
    xform = UsdGeom.Xformable(prim)
    xform.ClearXformOpOrder()
    if scale is not None:
        xform.AddScaleOp().Set(scale)
    xform.AddRotateXYZOp().Set(rotate)
    xform.AddTranslateOp().Set(translate)


def _wheel_local_positions() -> dict[str, Gf.Vec3f]:
    return {
        "FrontLeft": Gf.Vec3f(WHEEL_BASE * 0.5, WHEEL_TRACK * 0.5, WHEEL_RADIUS),
        "FrontRight": Gf.Vec3f(WHEEL_BASE * 0.5, -WHEEL_TRACK * 0.5, WHEEL_RADIUS),
        "RearLeft": Gf.Vec3f(-WHEEL_BASE * 0.5, WHEEL_TRACK * 0.5, WHEEL_RADIUS),
        "RearRight": Gf.Vec3f(-WHEEL_BASE * 0.5, -WHEEL_TRACK * 0.5, WHEEL_RADIUS),
    }


def _set_live_rover_pose(
    rover: dict[str, object],
    terrain_sampler,
    center_position: Gf.Vec3f,
    direction: np.ndarray,
) -> None:
    forward_xy = _normalize_xy(direction)
    wheel_contacts = _wheel_contacts(terrain_sampler, center_position, forward_xy)
    normal = _normal_from_wheel_contacts(wheel_contacts)
    ground_z = float(np.mean([contact[2] for contact in wheel_contacts.values()]))
    transform = _vehicle_transform(
        position=np.asarray([float(center_position[0]), float(center_position[1]), ground_z], dtype=np.float32),
        forward_xy=forward_xy,
        normal=np.asarray(normal, dtype=np.float32),
    )
    rover["root_transform"].Set(transform)


def _wheel_contacts(
    terrain_sampler,
    center_position: Gf.Vec3f,
    forward: np.ndarray,
) -> dict[str, tuple[float, float, float]]:
    right = np.asarray([forward[1], -forward[0]], dtype=np.float32)
    center_xy = np.asarray([float(center_position[0]), float(center_position[1])], dtype=np.float32)

    contacts = {}
    for name, local_position in _wheel_local_positions().items():
        xy = center_xy + forward * float(local_position[0]) + right * float(local_position[1])
        z = terrain_sampler.sample(float(xy[0]), float(xy[1]))
        contacts[name] = (float(xy[0]), float(xy[1]), float(z))
    return contacts


def _normal_from_wheel_contacts(contacts: dict[str, tuple[float, float, float]]) -> tuple[float, float, float]:
    front = 0.5 * (np.asarray(contacts["FrontLeft"]) + np.asarray(contacts["FrontRight"]))
    rear = 0.5 * (np.asarray(contacts["RearLeft"]) + np.asarray(contacts["RearRight"]))
    left = 0.5 * (np.asarray(contacts["FrontLeft"]) + np.asarray(contacts["RearLeft"]))
    right = 0.5 * (np.asarray(contacts["FrontRight"]) + np.asarray(contacts["RearRight"]))
    forward_axis = front - rear
    right_axis = right - left
    normal = np.cross(forward_axis, right_axis)
    if normal[2] < 0.0:
        normal = -normal
    normal /= max(float(np.linalg.norm(normal)), 1e-6)
    return float(normal[0]), float(normal[1]), float(normal[2])


def _vehicle_transform(position: np.ndarray, forward_xy: np.ndarray, normal: np.ndarray) -> Gf.Matrix4d:
    up = normal / max(float(np.linalg.norm(normal)), 1e-6)
    horizontal_forward = np.asarray([forward_xy[0], forward_xy[1], 0.0], dtype=np.float32)
    right = np.cross(horizontal_forward, up)
    if np.linalg.norm(right) < 1e-6:
        right = np.asarray([forward_xy[1], -forward_xy[0], 0.0], dtype=np.float32)
    right /= max(float(np.linalg.norm(right)), 1e-6)
    forward = np.cross(up, right)
    forward /= max(float(np.linalg.norm(forward)), 1e-6)

    matrix = Gf.Matrix4d(1.0)
    matrix.SetRow(0, Gf.Vec4d(float(forward[0]), float(forward[1]), float(forward[2]), 0.0))
    matrix.SetRow(1, Gf.Vec4d(float(right[0]), float(right[1]), float(right[2]), 0.0))
    matrix.SetRow(2, Gf.Vec4d(float(up[0]), float(up[1]), float(up[2]), 0.0))
    matrix.SetRow(3, Gf.Vec4d(float(position[0]), float(position[1]), float(position[2]), 1.0))
    return matrix


def _normalize_xy(direction: np.ndarray) -> np.ndarray:
    xy = np.asarray([float(direction[0]), float(direction[1])], dtype=np.float32)
    length = float(np.linalg.norm(xy))
    if length < 1e-6:
        return np.asarray([1.0, 0.0], dtype=np.float32)
    return xy / length


def _set_active_camera() -> None:
    try:
        from omni.kit.viewport.utility import get_active_viewport  # noqa: PLC0415

        viewport = get_active_viewport()
        if viewport is not None:
            viewport.camera_path = Sdf.Path("/World/Camera")
    except Exception as exc:
        print(f"Could not set active viewport camera: {exc}", flush=True)


def _set_overhead_camera(stage, points: list[Gf.Vec3f]) -> None:
    camera = UsdGeom.Camera(stage.GetPrimAtPath("/World/Camera"))
    if not camera.GetPrim().IsValid():
        camera = UsdGeom.Camera.Define(stage, "/World/Camera")

    xy = np.asarray([[float(point[0]), float(point[1])] for point in points], dtype=np.float32)
    center = xy.mean(axis=0)
    span = np.ptp(xy, axis=0)
    altitude = max(18.0, float(max(span) * 1.2))

    xform = UsdGeom.Xformable(camera.GetPrim())
    xform.ClearXformOpOrder()
    xform.AddTranslateOp().Set(Gf.Vec3f(float(center[0]), float(center[1]), altitude))
    xform.AddRotateXYZOp().Set(Gf.Vec3f(0.0, 0.0, 0.0))
    camera.CreateFocalLengthAttr(18.0)
    camera.CreateClippingRangeAttr(Gf.Vec2f(0.1, 1000.0))


def _set_translate(prim, position: Gf.Vec3f) -> None:
    xform = UsdGeom.Xformable(prim)
    for op in xform.GetOrderedXformOps():
        if op.GetOpType() == UsdGeom.XformOp.TypeTranslate:
            op.Set(position)
            return
    xform.AddTranslateOp().Set(position)


def _cumulative_distance(points: list[Gf.Vec3f]) -> np.ndarray:
    distances = [0.0]
    for first, second in zip(points[:-1], points[1:]):
        step = np.linalg.norm(
            [
                float(second[0] - first[0]),
                float(second[1] - first[1]),
                float(second[2] - first[2]),
            ]
        )
        distances.append(distances[-1] + float(step))
    return np.asarray(distances, dtype=np.float32)


def _interpolate_path(
    points: list[Gf.Vec3f],
    cumulative_distance: np.ndarray,
    target_distance: float,
) -> Gf.Vec3f:
    index = int(np.searchsorted(cumulative_distance, target_distance, side="right") - 1)
    index = max(0, min(index, len(points) - 2))
    start = points[index]
    end = points[index + 1]
    segment_length = float(cumulative_distance[index + 1] - cumulative_distance[index])
    if segment_length <= 1e-6:
        return start

    fraction = (target_distance - float(cumulative_distance[index])) / segment_length
    return Gf.Vec3f(
        float(start[0] + (end[0] - start[0]) * fraction),
        float(start[1] + (end[1] - start[1]) * fraction),
        float(start[2] + (end[2] - start[2]) * fraction),
    )


def _direction_at_distance(
    points: list[Gf.Vec3f],
    cumulative_distance: np.ndarray,
    target_distance: float,
) -> np.ndarray:
    index = int(np.searchsorted(cumulative_distance, target_distance, side="right") - 1)
    index = max(0, min(index, len(points) - 2))
    start = points[index]
    end = points[index + 1]
    dx = float(end[0] - start[0])
    dy = float(end[1] - start[1])
    if abs(dx) < 1e-6 and abs(dy) < 1e-6:
        return np.asarray([1.0, 0.0], dtype=np.float32)
    return np.asarray([dx, dy], dtype=np.float32)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        raise
    finally:
        simulation_app.close()
