from argparse import ArgumentParser
from pathlib import Path
import time
import traceback

import numpy as np
from isaacsim import SimulationApp


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCENE = PROJECT_ROOT / "outputs" / "isaac" / "desert_heightfield_scene.usd"
DEFAULT_PATH = PROJECT_ROOT / "outputs" / "perception" / "local_path.npz"
DEFAULT_HEIGHTFIELD = PROJECT_ROOT / "outputs" / "perception" / "local_heightfield.npz"
ROVER_PATH = "/World/RoverPlaceholder"


def parse_args():
    parser = ArgumentParser(description="Show a live rover path demo in Isaac Sim GUI.")
    parser.add_argument("--scene", default=str(DEFAULT_SCENE), help="USD scene to open.")
    parser.add_argument("--path", default=str(DEFAULT_PATH), help="local_path.npz generated by local planner.")
    parser.add_argument(
        "--heightfield",
        default=str(DEFAULT_HEIGHTFIELD),
        help="local_heightfield.npz generated from depth.",
    )
    parser.add_argument("--speed", type=float, default=1.0, help="Rover speed in meters per second.")
    parser.add_argument(
        "--frames",
        type=int,
        default=0,
        help="Number of frames to run before exit. 0 means run until the window closes.",
    )
    return parser.parse_args()


args = parse_args()
scene_path = Path(args.scene).expanduser().resolve()
path_path = Path(args.path).expanduser().resolve()
heightfield_path = Path(args.heightfield).expanduser().resolve()

if not scene_path.exists():
    raise FileNotFoundError(f"USD scene does not exist: {scene_path}")
if not path_path.exists():
    raise FileNotFoundError(f"local path does not exist: {path_path}")
if not heightfield_path.exists():
    raise FileNotFoundError(f"local heightfield does not exist: {heightfield_path}")
if args.speed <= 0:
    raise ValueError("speed must be positive")
if args.frames < 0:
    raise ValueError("frames must be non-negative")

simulation_app = SimulationApp({"headless": False, "open_usd": str(scene_path)})

import omni.usd  # noqa: E402
from pxr import Gf, Sdf, UsdGeom  # noqa: E402


def main() -> None:
    stage = _wait_for_stage()
    rover_prim = stage.GetPrimAtPath(ROVER_PATH)
    if not rover_prim.IsValid():
        raise RuntimeError(f"Rover prim does not exist: {ROVER_PATH}")

    world_points = _load_world_path()
    if len(world_points) < 2:
        raise RuntimeError("local path must contain at least two points")

    _draw_path_markers(stage, world_points)
    _set_active_camera()

    cumulative_distance = _cumulative_distance(world_points)
    total_distance = float(cumulative_distance[-1])
    start_time = time.monotonic()
    frame_count = 0

    print(f"Opened scene: {scene_path}", flush=True)
    print(f"Loaded path points: {len(world_points)}", flush=True)
    print(f"Path length: {total_distance:.2f} m", flush=True)
    print("Close the Isaac window to stop the demo.", flush=True)

    while simulation_app.is_running():
        elapsed = time.monotonic() - start_time
        distance = (elapsed * args.speed) % total_distance
        position = _interpolate_path(world_points, cumulative_distance, distance)
        _set_translate(rover_prim, position)
        simulation_app.update()

        frame_count += 1
        if args.frames and frame_count >= args.frames:
            break


def _wait_for_stage():
    usd_context = omni.usd.get_context()
    for _ in range(60):
        simulation_app.update()
        stage = usd_context.get_stage()
        if stage is not None:
            return stage
    raise RuntimeError("Isaac USD stage was not loaded")


def _load_world_path() -> list[Gf.Vec3f]:
    path_data = np.load(path_path)
    heightfield_data = np.load(heightfield_path)

    path = path_data["path"]
    origin_xy = path_data["origin_xy"].astype(np.float32)
    resolution = float(path_data["resolution"])
    elevation = heightfield_data["elevation"]

    points: list[Gf.Vec3f] = []
    for row, col in path:
        row = int(row)
        col = int(col)
        x = float(origin_xy[0] + col * resolution)
        y = float(origin_xy[1] + row * resolution)
        z = _safe_elevation(elevation, row, col) + 0.35
        points.append(Gf.Vec3f(x, y, z))
    return points


def _safe_elevation(elevation: np.ndarray, row: int, col: int) -> float:
    value = float(elevation[row, col])
    if np.isfinite(value):
        return value

    finite = np.isfinite(elevation)
    if finite.any():
        return float(np.median(elevation[finite]))
    return 0.0


def _draw_path_markers(stage, points: list[Gf.Vec3f]) -> None:
    _draw_sphere(stage, "/World/LivePath/Start", points[0], radius=0.22, color=(0.0, 1.0, 0.0))
    _draw_sphere(stage, "/World/LivePath/Goal", points[-1], radius=0.22, color=(1.0, 0.0, 0.0))
    stride = max(1, len(points) // 40)
    for index, point in enumerate(points[::stride]):
        marker = _draw_sphere(
            stage,
            f"/World/LivePath/Point_{index:03d}",
            point,
            radius=0.08,
            color=(1.0, 1.0, 1.0),
        )
        marker.GetPrim().SetActive(True)


def _draw_sphere(
    stage,
    path: str,
    position: Gf.Vec3f,
    radius: float,
    color: tuple[float, float, float],
) -> UsdGeom.Sphere:
    sphere = UsdGeom.Sphere.Define(stage, path)
    sphere.CreateRadiusAttr(radius)
    _set_translate(sphere.GetPrim(), position)
    sphere.CreateDisplayColorAttr([Gf.Vec3f(*color)])
    return sphere


def _set_active_camera() -> None:
    try:
        from omni.kit.viewport.utility import get_active_viewport  # noqa: PLC0415

        viewport = get_active_viewport()
        if viewport is not None:
            viewport.camera_path = Sdf.Path("/World/Camera")
    except Exception as exc:
        print(f"Could not set active viewport camera: {exc}", flush=True)


def _set_translate(prim, position: Gf.Vec3f) -> None:
    xform = UsdGeom.Xformable(prim)
    for op in xform.GetOrderedXformOps():
        if op.GetOpType() == UsdGeom.XformOp.TypeTranslate:
            op.Set(position)
            return
    xform.AddTranslateOp().Set(position)


def _cumulative_distance(points: list[Gf.Vec3f]) -> np.ndarray:
    distances = [0.0]
    for first, second in zip(points[:-1], points[1:]):
        step = np.linalg.norm(
            [
                float(second[0] - first[0]),
                float(second[1] - first[1]),
                float(second[2] - first[2]),
            ]
        )
        distances.append(distances[-1] + float(step))
    return np.asarray(distances, dtype=np.float32)


def _interpolate_path(
    points: list[Gf.Vec3f],
    cumulative_distance: np.ndarray,
    target_distance: float,
) -> Gf.Vec3f:
    index = int(np.searchsorted(cumulative_distance, target_distance, side="right") - 1)
    index = max(0, min(index, len(points) - 2))
    start = points[index]
    end = points[index + 1]
    segment_length = float(cumulative_distance[index + 1] - cumulative_distance[index])
    if segment_length <= 1e-6:
        return start

    fraction = (target_distance - float(cumulative_distance[index])) / segment_length
    return Gf.Vec3f(
        float(start[0] + (end[0] - start[0]) * fraction),
        float(start[1] + (end[1] - start[1]) * fraction),
        float(start[2] + (end[2] - start[2]) * fraction),
    )


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        raise
    finally:
        simulation_app.close()
